### ISSUE TITLE
Sequence Number setting

### ISSUE THREAD

**Issue by tomerweller** [LedgerHQ/app-stellar#40]
Add a `Sequence Number` setting: `Displayed` or `NOT Displayed`. Default to Not

**Comment by overcat** [comment]
Hi @tomerweller, I'm currently working on a big refactoring and I expect to do the following in this refactoring:

1. Refactor the app according to the latest app-boilerplate code provided by Ledger
2. Add Simple mode (allow users to hide Sequence, Fee and other information)
3. Add complete e2e tests
4. Refactor existing unit tests
5. Optimize UX

If you feel there is anything in the app that needs optimization, please let me know so I can include it in the refactoring.

The current work is still in progress, I hope to finish it and merge it into this repo in the next quarter, the refactored code is at https://github.com/overcat/ledger-stellar

**Comment by tomerweller** [comment]
> Add Simple mode (allow users to hide Sequence, Fee and other information)
What other information? I would consider having one setting per option, rather than a blanket simple mode. For example, I can imagine some people might want to see fees but not seq nums. 

Overall I think the UX is pretty good right now after the last set of changes. 

I would optimize for payments, given that they're probably the most common operation. For example, the screen `Operation Type: Payment` is pretty redundant because the next screen is `Send: 1 XLM`. Maybe other operation type screens could also be removed.

**Comment by overcat** [comment]
> What other information? I would consider having one setting per option, rather than a blanket simple mode. For example, I can imagine some people might want to see fees but not seq nums.

Since fee on Stellar is consistently low to almost negligible, I don't think most users care about it, but I wonder if there are some corner cases here that cause fees to be high, so I agree with you to keep it.

Also I would like to ask, for `time_bounds`, `ledger_bounds`, `min_sequence_number`, `min_sequence_ledger_gap` and  `min_sequence_age`, do you think we should allow users to set whether to show them or not? For `ledger_bounds`, `min_sequence_number`, `min_sequence_ledger_gap` and `min_sequence_age`, I personally think that it is not necessary to provide setting items, because I think most transactions will not contain this information. But for `time_bounds`, most transactions will set a `time_bounds`, should we consider hiding it by default?

> I would optimize for payments, given that they're probably the most common operation. For example, the screen Operation Type: Payment is pretty redundant because the next screen is Send: 1 XLM. Maybe other operation type screens could also be removed.

Yes, I will revisit it to remove unnecessary screens.

**Comment by tomerweller** [comment]
I would not add a setting for optional fields like the various cap21 fields and timebounds. If they exist - I think we should show them. As for upper timebound, yes it's very common but I think it's worth showing anyway, and with the latest timestamp changes the ux is much better anyway.
